# 这是之前最简单的配置

server:
  port: 80
spring:
  application:
    name: gateway-common-80
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:  # 注意看，这里叫routes 说明内容是一个数组，- 就表示数组
        - id: goods_path   # 唯一id,随便起，但是不能重名
          uri: http://localhost:7001  #要转发的地址,这个可以是指定的url，也可以是注册中心的服务名（后边会讲）
          predicates:
            - Path=/goods/** # 匹配的路径** 代表通配

        - id: order_path
          uri: http://localhost:8001
          predicates:
            - Path=/order/**

        - id: user_path
          uri: http://localhost:9001
          predicates:
            - Path=/user/**


